### ISSUE TITLE
Project directory ./ is not empty

### ISSUE THREAD

**Issue by lsv** [mageinferno/magento2-docker-compose#37]
```
setup_1   | Installing magento/project-community-edition (2.1.2)
setup_1   | 
setup_1   |                                       
setup_1   |   [InvalidArgumentException]          
setup_1   |   Project directory ./ is not empty.  
setup_1   |                                       
setup_1   | 
setup_1   | create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]
setup_1   | 
setup_1   | ln: failed to create symbolic link './var/composer_home': No such file or directory
setup_1   | chmod: cannot access './bin/magento': No such file or directory
setup_1   | Installing composer dependencies...
setup_1   | The "hirak/prestissimo" plugin was skipped because it requires a Plugin API version ("~1.0.0-alpha10") that does not match your Composer installation ("1.1.0"). You may need to run composer update with the "--no-plugins" option.
setup_1   | Composer could not find a composer.json file in /var/www/html
setup_1   | To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
setup_1   | Could not open input file: ./bin/magento
setup_1   | Running Magento 2 setup script...
setup_1   | Could not open input file: ./bin/magento
setup_1   | The setup script has completed execution.
magento2dockercompose_setup_1 exited with code 0
phpfpm_1  | Could not open input file: /var/www/html/bin/magento-php
phpfpm_1  | Could not open input file: /var/www/html/update/cron.php
phpfpm_1  | Could not open input file: /var/www/html/bin/magento-php
```

My `docker-compose.override.yml` file

```
phpfpm:
  environment:
    - PHP_MEMORY_LIMIT=4G
    - MAGE_APP_MODE=dev

appdata:
  volumes:
    - ~/.composer:/var/www/.composer
    - ./html/app/code:/var/www/html/app/code
    - ./html/app/design:/var/www/html/app/design

setup:
  environment:
    - PHP_MEMORY_LIMIT=4G
    - MAGE_APP_MODE=dev
    - M2SETUP_USE_SAMPLE_DATA=true
    - M2SETUP_USE_ARCHIVE=false
```

docker-compose.yml has not been touched.

What I did was

```
$ git clone https://github.com/mageinferno/magento2-docker-compose.git
$ cd magento2-docker-compose
// changed docker-compose.override.yml
$ docker-compose up
```
