### ISSUE TITLE
Deprecated Functionality: Function mcrypt_module_open() is deprecated with php:7.1-fpm-0

### ISSUE THREAD

**Issue by iandd0824** [mageinferno/magento2-docker-compose#54]
Try to install the version 2.1.4 and run into the deprecated exception if I use the php version magento2-php:7.1-fpm-0 in setup container.

There is no deprecated exception with magento2-php:7.0-fpm-0.

docker-compose.yml
```
setup:
  image: mageinferno/magento2-php:7.1-fpm-0
  command: /usr/local/bin/mage-setup
  links:
    - db
  volumes_from:
    - appdata
  env_file: env/setup.env
```

Command
```
$ docker-compose run --rm setup
```

Deprecated Exception
```
[Progress: 114 / 425]
Module 'Magento_Customer':
[Progress: 115 / 425]
Module 'Magento_BundleImportExport':
[Progress: 116 / 425]
Module 'Magento_CacheInvalidate':
[Progress: 117 / 425]
Module 'Magento_AdminNotification':
[Progress: 118 / 425]
Module 'Magento_Indexer':
Running schema recurring...


[Exception] Deprecated Functionality: Function mcrypt_module_open() is deprecated in /var/www/html/vendor/magento/framework/Encryption/Crypt.php on line 54

```
